# Generated by Django 5.2.6 on 2025-09-21 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('end_datetime', models.DateTimeField(verbose_name='Data e Hora de Término')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'appointments',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('end_time', models.TimeField(verbose_name='Hora de Término')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Agenda do Barbeiro',
                'verbose_name_plural': 'Agendas dos Barbeiros',
                'db_table': 'barber_schedules',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
