# Generated by Django 5.2.6 on 2025-09-21 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_unique_together'),
        ('barbershop', '0003_service_image_alter_barbershop_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barberschedule',
            unique_together={('barber', 'barbershop', 'weekday')},
        ),
    ]
