# Generated by Django 5.2.6 on 2025-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0002_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro'),
        ),
        migrations.AddField(
            model_name='review',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbershop.barbershop', verbose_name='Barbearia'),
        ),
        migrations.AddField(
            model_name='review',
            name='barbershop_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbershop.barbershopcustomer', verbose_name='Cliente da Barbearia'),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbershop.service', verbose_name='Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('barbershop_customer', 'barber', 'service', 'barbershop')},
        ),
    ]
