# Generated by Django 5.2.6 on 2025-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('BARBER', 'Barbeiro'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=10, verbose_name='Função'),
        ),
    ]
