# Generated by Django 5.2.6 on 2025-09-21 00:44

import functools
import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(utils.file_uploads.encrypted_filename, *(), **{'app_name': True, 'base_folder': 'profile_pictures', 'default_subfolder': 'others', 'subfolder_attr': 'role', 'subfolder_map': {'ADMIN': 'admins', 'BARBER': 'barbers', 'CLIENT': 'clients'}}), verbose_name='Foto de Perfil'),
        ),
    ]
