# Generated by Django 5.2.6 on 2025-09-21 12:27

import functools
import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(utils.file_uploads.encrypted_filename, *(), **{'app_name': True, 'base_folder': 'services', 'default_subfolder': 'barbershops'}), verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(utils.file_uploads.encrypted_filename, *(), **{'app_name': True, 'base_folder': 'logos', 'default_subfolder': 'barbershops'}), verbose_name='Logo'),
        ),
    ]
