# Generated by Django 5.2.6 on 2025-09-19 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barbershops/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BarbershopCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Última Visita')),
            ],
            options={
                'verbose_name': 'Cliente da Barbearia',
                'verbose_name_plural': 'Clientes da Barbearia',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['barbershop', 'name'],
            },
        ),
    ]
