# Generated by Django 5.2.6 on 2025-09-18 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershops', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='barbershopcustomer',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_customers', to='barbershops.barbershop', verbose_name='Barbearia'),
        ),
        migrations.AddField(
            model_name='barbershopcustomer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbershop_customers', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='service',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbershops.barbershop', verbose_name='Barbearia'),
        ),
        migrations.AlterUniqueTogether(
            name='barbershopcustomer',
            unique_together={('customer', 'barbershop')},
        ),
    ]
