# Generated by Django 5.2.6 on 2025-09-21 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='ID da Transação'),
        ),
    ]
