# Generated by Django 5.2.6 on 2025-09-19 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbershops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barber_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbershops.barbershop', verbose_name='Barbearia'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbershops.barbershopcustomer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbershops.service', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='barberschedule',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro'),
        ),
        migrations.AddField(
            model_name='barberschedule',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_schedules', to='barbershops.barbershop', verbose_name='Barbearia'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('customer', 'barber', 'service', 'barbershop')},
        ),
        migrations.AlterUniqueTogether(
            name='barberschedule',
            unique_together={('barber', 'barbershop')},
        ),
    ]
